name: ustabul_mobile
description: UstaBul mobile client for iOS and Android.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
